### ISSUE TITLE
Deleting openshift build while running in Jenkins can leave build in build queue

### ISSUE THREAD

**Issue by jim-minter** [fabric8io/openshift-jenkins-sync-plugin#104]
I'm running a openshift build from the following Jenkinsfile:
```
node('nodejs') {
  stage 'build'
  openshiftBuild(buildConfig: 'nodejs-ex', showBuildLogs: 'true')
  stage 'deploy'
  openshiftDeploy(deploymentConfig: 'nodejs-ex')
}
```

If I delete the build controller while the build is running, I sometimes see the following stuck in the Jenkins UI:

Build Queue (1)
part of nodejs-ex #1

**Comment by jim-minter** [comment]
@gabemontero
@jimmidyson 

I think there's a collection of issues around deletion of builds and buildconfigs that ought to be worked through.

* there's no listener in Jenkins for deletion of build objects (we just watch for cancellations)
* there seem to be edge cases where build executors are left registered when they should probably be cleaned up when builds are deleted early
* ditto where /var/lib/jenkins/jobs/$JOB isn't cleaned out properly when the buildconfig is deleted and this causes problems if an identical buildconfig is later reinstantiated.

https://github.com/jim-minter/openshift-sync-plugin/commit/issue104 might be a starting point on some of this but it's incomplete - am concerned about races between deletions of builds and buildconfigs.  Also lots of tracebacks in the jenkins log when deleting running builds even though the UI behaviour looks ok.

```
INFO: Patching build in namespace demo with name: nodejs-ex-pipeline-1 phase: Running
Nov 11, 2016 11:51:59 AM io.fabric8.jenkins.openshiftsync.BuildSyncRunListener upsertBuild
INFO: Patching build in namespace demo with name: nodejs-ex-pipeline-1 phase: Running
Nov 11, 2016 11:52:00 AM io.fabric8.jenkins.openshiftsync.BuildSyncRunListener upsertBuild
INFO: Patching build in namespace demo with name: nodejs-ex-pipeline-1 phase: Running
Nov 11, 2016 11:52:00 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
INFO: Terminating Kubernetes instance for slave nodejs-a604511a92f
Nov 11, 2016 11:52:00 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
INFO: Terminated Kubernetes instance for slave nodejs-a604511a92f
Nov 11, 2016 11:52:00 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
INFO: Disconnected computer nodejs-a604511a92f
Nov 11, 2016 11:52:00 AM org.jenkinsci.plugins.workflow.job.WorkflowRun finish
INFO: nodejs-ex-pipeline #1 completed: ABORTED
Nov 11, 2016 11:52:00 AM io.fabric8.jenkins.openshiftsync.BuildSyncRunListener upsertBuild
INFO: Patching build in namespace demo with name: nodejs-ex-pipeline-1 phase: Cancelled
Nov 11, 2016 11:52:00 AM io.fabric8.jenkins.openshiftsync.BuildSyncRunListener upsertBuild
INFO: Patching build failed with 404
Nov 11, 2016 11:52:00 AM io.fabric8.jenkins.openshiftsync.BuildSyncRunListener onCompleted
INFO: onCompleted job/nodejs-ex-pipeline/1/
Nov 11, 2016 11:52:00 AM io.fabric8.jenkins.openshiftsync.BuildSyncRunListener upsertBuild
INFO: Patching build in namespace demo with name: nodejs-ex-pipeline-1 phase: Cancelled
Nov 11, 2016 11:52:00 AM io.fabric8.jenkins.openshiftsync.BuildSyncRunListener upsertBuild
INFO: Patching build failed with 404
Nov 11, 2016 11:52:00 AM io.fabric8.jenkins.openshiftsync.BuildSyncRunListener onFinalized
INFO: onFinalized job/nodejs-ex-pipeline/1/
Nov 11, 2016 11:52:01 AM org.jenkinsci.plugins.workflow.cps.CpsStepContext completed
WARNING: already completed CpsStepContext[6:openshiftBuild]:Owner[nodejs-ex-pipeline/1:nodejs-ex-pipeline #1]
java.lang.IllegalStateException: delivered here
	at org.jenkinsci.plugins.workflow.cps.CpsStepContext.completed(CpsStepContext.java:351)
	at org.jenkinsci.plugins.workflow.cps.CpsStepContext.onFailure(CpsStepContext.java:327)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:56)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Nov 11, 2016 11:52:01 AM org.jenkinsci.plugins.workflow.cps.CpsStepContext completed
INFO: new failure
com.openshift.restclient.NotFoundException: builds "nodejs-ex-7" not found builds "nodejs-ex-7" not found
	at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.createOpenShiftException(ResponseCodeInterceptor.java:112)
	at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.intercept(ResponseCodeInterceptor.java:65)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
	at okhttp3.RealCall.execute(RealCall.java:60)
	at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:217)
	at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:194)
	at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:183)
	at com.openshift.internal.restclient.DefaultClient.get(DefaultClient.java:291)
	at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftBuilder.waitOnBuild(IOpenShiftBuilder.java:125)
	at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftBuilder.coreLogic(IOpenShiftBuilder.java:250)
	at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftPlugin.doItCore(IOpenShiftPlugin.java:305)
	at com.openshift.jenkins.plugins.pipeline.dsl.OpenShiftBuilderExecution.run(OpenShiftBuilderExecution.java:42)
	at com.openshift.jenkins.plugins.pipeline.dsl.OpenShiftBuilderExecution.run(OpenShiftBuilderExecution.java:18)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:52)
	at hudson.security.ACL.impersonate(ACL.java:213)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:49)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Nov 11, 2016 11:52:01 AM org.jenkinsci.plugins.workflow.cps.CpsStepContext completed
INFO: previously delivered here
java.lang.Throwable
	at org.jenkinsci.plugins.workflow.cps.CpsStepContext.completed(CpsStepContext.java:339)
	at org.jenkinsci.plugins.workflow.cps.CpsStepContext.onFailure(CpsStepContext.java:327)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun$5.onSuccess(WorkflowRun.java:327)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun$5.onSuccess(WorkflowRun.java:323)
	at org.jenkinsci.plugins.workflow.support.concurrent.Futures$1.run(Futures.java:150)
	at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:253)
	at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:149)
	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:134)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:170)
	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:53)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$5.onSuccess(CpsFlowExecution.java:703)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$5.onSuccess(CpsFlowExecution.java:690)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$4$1.run(CpsFlowExecution.java:627)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.run(CpsVmExecutorService.java:35)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Nov 11, 2016 11:52:01 AM org.jenkinsci.plugins.workflow.cps.CpsStepContext completed
INFO: earlier failure
org.jenkinsci.plugins.workflow.steps.FlowInterruptedException
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.doTerm(WorkflowRun.java:322)
	at io.fabric8.jenkins.openshiftsync.JenkinsUtils.cancelRunningBuild(JenkinsUtils.java:129)
	at io.fabric8.jenkins.openshiftsync.JenkinsUtils.cancelBuild(JenkinsUtils.java:117)
	at io.fabric8.jenkins.openshiftsync.CancelledBuildWatcher$1.call(CancelledBuildWatcher.java:112)
	at io.fabric8.jenkins.openshiftsync.CancelledBuildWatcher$1.call(CancelledBuildWatcher.java:1)
	at hudson.security.ACL.impersonate(ACL.java:213)
	at io.fabric8.jenkins.openshiftsync.CancelledBuildWatcher.buildDeleted(CancelledBuildWatcher.java:109)
	at io.fabric8.jenkins.openshiftsync.CancelledBuildWatcher.eventReceived(CancelledBuildWatcher.java:87)
	at io.fabric8.jenkins.openshiftsync.CancelledBuildWatcher.eventReceived(CancelledBuildWatcher.java:1)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onMessage(WatchConnectionManager.java:215)
	at okhttp3.internal.ws.RealWebSocket$1.onMessage(RealWebSocket.java:62)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:242)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:108)
	at okhttp3.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
	at okhttp3.ws.WebSocketCall.createWebSocket(WebSocketCall.java:152)
	at okhttp3.ws.WebSocketCall.access$000(WebSocketCall.java:41)
	at okhttp3.ws.WebSocketCall$1.onResponse(WebSocketCall.java:97)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Nov 11, 2016 11:52:01 AM hudson.slaves.NodeProvisioner$2 run
INFO: Kubernetes Pod Template provisioning successfully completed. We have now 3 computer(s)
Nov 11, 2016 11:52:36 AM io.fabric8.jenkins.openshiftsync.PipelineJobListener onDeleted
INFO: Deleting BuildConfig NamespaceName{demo:nodejs-ex-pipeline}
```

**Comment by gabemontero** [comment]
@bparees just in case FYI

**Comment by jimmidyson** [comment]
You are correct there is no deletion of Jenkins builds when an OpenShift Build is deleted. Don't think that's a big deal for now personally but we can think about that in future.

As for deleting BuildConfigs during a Build run, that is of course an issue that needs fixing. We delegate deleting of Jenkins jobs to Jenkins itself, it should perform all cleanup related to the job (files, etc). Looking through the code, Jenkins attempts to interrupt running builds, but as discussed in other BZ issues this requires Jenkins pipeline steps to correctly handle interruption. Otherwise they keep running... which is why you see the files/dirs remaining even after job deletion. I'd say this is a bug in Jenkins or the pipeline steps. I have already implemented a workaround for cancelling builds with pipeline steps that don't correctly handle interruption & could reuse that logic here, but hate working around issues in case they have unforeseen knock on effects. Of course it's always more difficult to remove code than to add it in...

**Comment by jimmidyson** [comment]
Relevant code in Jenkins (https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/Job.java#L265-L277):

```java
    protected void performDelete() throws IOException, InterruptedException {
        // if a build is in progress. Cancel it.
        RunT lb = getLastBuild();
        if (lb != null) {
            Executor e = lb.getExecutor();
            if (e != null) {
                e.interrupt();
                // should we block until the build is cancelled?
            }
        }
        super.performDelete();
    }
```

Notice the comment... answer: yes!

**Comment by sspeiche** [comment]
@jimmidyson Is this something you can push in the jenkins community? Seems like we have some evidence to help make the case to support this. Can we modify this and try out the fix ourselves to validate it?

**Comment by jimmidyson** [comment]
@sspeiche For a change like that we'll need to try to understand why they don't already do it - there must be some reason why it's difficult or not desirable. Do we have any Jenkins core committers that could look at this?

**Comment by gabemontero** [comment]
So things have evolved a bit since the last set of commentary in Nov 2016:

- Jenkins job delete has been totally reworked;  from the delete() method at  https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/Job.java#L673-L675 to the delete() and performDelete methods at  https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/AbstractItem.java#L581-L692 .... it would appear some of the issues @jimmidyson noted in https://github.com/openshift/jenkins-sync-plugin/issues/104#issuecomment-259951013 have been resolved, including the deletion of `/var/lib/jenkins/jobs/$JOB`

- @jim-minter 's check for 404 / not found on openshift patch is now in:  https://github.com/openshift/jenkins-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/BuildSyncRunListener.java#L315

- General (with no explicit proof) observation: pipeline jobs seem to be doing better with getting interrupted; I see it consistently during failures in the openshift extended tests

I'm going to experiment a bit with this scenario, along with hopefully inserting the remaining pieced: openshift build deletion -> jenkins run deletion (or at least cancellation).

@bparees I left you on the assignees list for now just in case you wanted that, but certainly remove yourself as you see fit

**Comment by bparees** [comment]
@gabemontero all yours.  The main issue from what @jim-minter described that concerns me is the case where the openshift build object gets deleted while running and jenkins doesn't seem to handle it properly (or didn't at the time. not clear to me from this thread if that's one of the things that's been fixed)

**Comment by gabemontero** [comment]
The remaining piece from @jim-minter 's prototype commit was for handling build object deletion.  I have a version of that change that is copacetic with the current code level and plan to include that in my testing.

**Comment by gabemontero** [comment]
BC deletes look fine, as well as recreates and the starting of subsequent builds afterwards.  And I have an augmented version of @jim-minter 's build delete prototype that I'm about to push in a PR.

As @jim-minter alluded to earlier, some of our dependencies are a little chatty with stack traces, but the ones I found all looked benign to me.
