### ISSUE TITLE
Build status JSON doesn't include pipeline stages

### ISSUE THREAD

**Issue by spadgett** [fabric8io/openshift-jenkins-sync-plugin#48]
The stages array is empty in the JSON that is synced back to the OpenShift build object. I'm using the following repository, which has a Jenkinsfile with two stages.

https://github.com/rawlingsj/basic-jenkinsfile

Here is the JSON I see in the `openshift.io/jenkins-status-json` annotation:

```json
{
    "_links": {
        "self": {
            "href": "//job/ruby-sample-build/1/wfapi/describe"
        },
        "changesets": null,
        "pendingInputActions": null,
        "nextPendingInputAction": null,
        "artifacts": null
    },
    "id": "1",
    "name": "#1",
    "status": "SUCCESS",
    "startTimeMillis": 1462211831727,
    "endTimeMillis": 0,
    "durationMillis": 0,
    "queueDurationMillis": 17758,
    "pauseDurationMillis": 0,
    "stages": []
}
```

Here is the log from Jenkins:

```
INFO: Waiting for Pod to be scheduled (1/100): 303fc3b05ef6
May 02, 2016 5:57:23 PM io.fabric8.jenkins.openshiftsync.BuildSyncRunListener upsertBuild
INFO: replacing build in namespace default with name: ruby-sample-build-1 phase: Running
May 02, 2016 5:57:25 PM io.fabric8.jenkins.openshiftsync.BuildSyncRunListener upsertBuild
INFO: replacing build in namespace default with name: ruby-sample-build-1 phase: Running
May 02, 2016 5:57:26 PM hudson.TcpSlaveAgentListener$ConnectionHandler run
INFO: Accepted connection #1 from /172.17.0.3:59598
May 02, 2016 5:57:27 PM io.fabric8.jenkins.openshiftsync.BuildSyncRunListener upsertBuild
INFO: replacing build in namespace default with name: ruby-sample-build-1 phase: Running
May 02, 2016 5:57:29 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
INFO: Terminating Kubernetes instance for slave 303fc3b05ef6
May 02, 2016 5:57:29 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
INFO: Terminated Kubernetes instance for slave 303fc3b05ef6
May 02, 2016 5:57:29 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
INFO: Disconnected computer 303fc3b05ef6
May 02, 2016 5:57:29 PM hudson.remoting.AbstractByteArrayCommandTransport$1 handle
WARNING: Failed to construct Command
java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2353)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2822)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:804)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:301)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
	at hudson.remoting.AbstractByteArrayCommandTransport$1.handle(AbstractByteArrayCommandTransport.java:61)
	at org.jenkinsci.remoting.nio.NioChannelHub$2.run(NioChannelHub.java:594)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
May 02, 2016 5:57:29 PM org.jenkinsci.plugins.workflow.job.WorkflowRun finish
INFO: ruby-sample-build #1 completed: SUCCESS
May 02, 2016 5:57:29 PM io.fabric8.jenkins.openshiftsync.BuildSyncRunListener upsertBuild
INFO: replacing build in namespace default with name: ruby-sample-build-1 phase: Complete
May 02, 2016 5:57:29 PM io.fabric8.jenkins.openshiftsync.BuildSyncRunListener onCompleted
INFO: onCompleted job/ruby-sample-build/1/
May 02, 2016 5:57:29 PM io.fabric8.jenkins.openshiftsync.BuildSyncRunListener upsertBuild
INFO: replacing build in namespace default with name: ruby-sample-build-1 phase: Complete
May 02, 2016 5:57:29 PM io.fabric8.jenkins.openshiftsync.BuildSyncRunListener onFinalized
INFO: onFinalized job/ruby-sample-build/1/
May 02, 2016 5:57:35 PM hudson.slaves.NodeProvisioner$2 run
INFO: Kubernetes Pod Template provisioning successfully completed. We have now 2 computer(s)
```

@jimmidyson @bparees

**Comment by spadgett** [comment]
Here is the JSON I get hitting the URL directly at

https://jenkins-default.router.default.svc.cluster.local/job/ruby-sample-build/1/wfapi/describe

```json
{
  "_links": {
    "self": {
      "href": "/job/ruby-sample-build/1/wfapi/describe"
    }
  },
  "id": "1",
  "name": "#1",
  "status": "SUCCESS",
  "startTimeMillis": 1462211831727,
  "endTimeMillis": 1462211849378,
  "durationMillis": 82,
  "queueDurationMillis": 17569,
  "pauseDurationMillis": 0,
  "stages": [
    {
      "_links": {
        "self": {
          "href": "/job/ruby-sample-build/1/execution/node/5/wfapi/describe"
        }
      },
      "id": "5",
      "name": "first",
      "execNode": "303fc3b05ef6",
      "status": "SUCCESS",
      "startTimeMillis": 1462211849296,
      "durationMillis": 6,
      "pauseDurationMillis": 0
    },
    {
      "_links": {
        "self": {
          "href": "/job/ruby-sample-build/1/execution/node/7/wfapi/describe"
        }
      },
      "id": "7",
      "name": "second",
      "execNode": "303fc3b05ef6",
      "status": "SUCCESS",
      "startTimeMillis": 1462211849302,
      "durationMillis": 76,
      "pauseDurationMillis": 0
    }
  ]
}
```

**Comment by jimmidyson** [comment]
This is a temporary issue until https://github.com/jenkinsci/pipeline-stage-view-plugin/pull/11 is merged in the Pipeline REST API plugin. TODO added previously: https://github.com/fabric8io/openshift-jenkins-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/BuildSyncRunListener.java#L186-L189

**Comment by fabianofranz** [comment]
@spadgett @jimmidyson a new release happened a few hours ago:

https://github.com/jenkinsci/pipeline-stage-view-plugin/releases/tag/pipeline-stage-view-1.4

By any change this fix is present?

**Comment by jimmidyson** [comment]
Yes the fix is in that release - thanks for the heads up. I'll update the dependencies tomorrow.

**Comment by jimmidyson** [comment]
Damn the released artifact hasn't been deployed to Jenkins Artifactory so can't use it yet - raised https://issues.jenkins-ci.org/browse/JENKINS-34754 to request it.

**Comment by jimmidyson** [comment]
This is now fixed.

**Comment by spadgett** [comment]
Can confirm, it's fixed. Thanks @jimmidyson !

**Comment by jimmidyson** [comment]
Thanks for confirming :smile:
