### ISSUE TITLE
Sync plugin stops working after some time

### ISSUE THREAD

**Issue by spadgett** [fabric8io/openshift-jenkins-sync-plugin#58]
I've noticed that the sync plugin works well for a while, but eventually stops working. Builds started in OpenShift are stuck in New state and never kicked off in Jenkins.

Here is the tail of the Jenkins log:

```
INFO: onFinalized job/sample-pipeline/3/
java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.java:64)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:77)
	at com.squareup.okhttp.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:110)
	at com.squareup.okhttp.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:99)
	at com.squareup.okhttp.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
	at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:153)
	at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:40)
	at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:98)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "OkHttp Dispatcher" java.lang.IllegalStateException: closed
	at com.squareup.okhttp.internal.ws.WebSocketReader$FramedMessageSource.read(WebSocketReader.java:267)
	at okio.Buffer.writeAll(Buffer.java:956)
	at okio.RealBufferedSource.readUtf8(RealBufferedSource.java:163)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onMessage(WatchConnectionManager.java:166)
	at com.squareup.okhttp.internal.ws.RealWebSocket$1.onMessage(RealWebSocket.java:62)
	at com.squareup.okhttp.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:242)
	at com.squareup.okhttp.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:103)
	at com.squareup.okhttp.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
	at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:153)
	at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:40)
	at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:98)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "OkHttp Dispatcher" java.lang.IllegalStateException: closed
	at com.squareup.okhttp.internal.ws.WebSocketReader$FramedMessageSource.read(WebSocketReader.java:267)
	at okio.Buffer.writeAll(Buffer.java:956)
	at okio.RealBufferedSource.readUtf8(RealBufferedSource.java:163)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onMessage(WatchConnectionManager.java:166)
	at com.squareup.okhttp.internal.ws.RealWebSocket$1.onMessage(RealWebSocket.java:62)
	at com.squareup.okhttp.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:242)
	at com.squareup.okhttp.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:103)
	at com.squareup.okhttp.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
	at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:153)
	at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:40)
	at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:98)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
May 13, 2016 7:24:37 PM hudson.model.AsyncPeriodicWork$1 run
INFO: Started Workspace clean-up
May 13, 2016 7:24:37 PM hudson.model.AsyncPeriodicWork$1 run
INFO: Finished Workspace clean-up. 3 ms
```

/cc @bparees @jimmidyson

**Comment by spadgett** [comment]
There seems to be no way to cancel the build from OpenShift when it's in this state as well.

**Comment by spadgett** [comment]
Ran into this again. Here is the log.

```
May 16, 2016 2:04:46 PM io.fabric8.jenkins.openshiftsync.BuildSyncRunListener onFinalized
INFO: onFinalized job/sample-pipeline/19/
May 16, 2016 2:44:50 PM org.eclipse.jetty.util.log.JavaUtilLog warn
WARNING: Ignoring extra content ��
May 16, 2016 2:44:50 PM org.eclipse.jetty.util.log.JavaUtilLog warn
WARNING: Ignoring extra content ����R0�)"�

java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.java:64)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:77)
	at com.squareup.okhttp.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:110)
	at com.squareup.okhttp.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:99)
	at com.squareup.okhttp.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
	at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:153)
	at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:40)
	at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:98)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.java:64)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:77)
	at com.squareup.okhttp.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:110)
	at com.squareup.okhttp.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:99)
	at com.squareup.okhttp.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
	at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:153)
	at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:40)
	at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:98)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "OkHttp Dispatcher" java.lang.IllegalStateException: closed
	at com.squareup.okhttp.internal.ws.WebSocketReader$FramedMessageSource.read(WebSocketReader.java:267)
	at okio.Buffer.writeAll(Buffer.java:956)
	at okio.RealBufferedSource.readUtf8(RealBufferedSource.java:163)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onMessage(WatchConnectionManager.java:166)
	at com.squareup.okhttp.internal.ws.RealWebSocket$1.onMessage(RealWebSocket.java:62)
	at com.squareup.okhttp.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:242)
	at com.squareup.okhttp.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:103)
	at com.squareup.okhttp.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
	at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:153)
	at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:40)
	at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:98)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "OkHttp Dispatcher" java.lang.IllegalStateException: closed
	at com.squareup.okhttp.internal.ws.WebSocketReader$FramedMessageSource.read(WebSocketReader.java:267)
	at okio.Buffer.writeAll(Buffer.java:956)
	at okio.RealBufferedSource.readUtf8(RealBufferedSource.java:163)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onMessage(WatchConnectionManager.java:166)
	at com.squareup.okhttp.internal.ws.RealWebSocket$1.onMessage(RealWebSocket.java:62)
	at com.squareup.okhttp.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:242)
	at com.squareup.okhttp.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:103)
	at com.squareup.okhttp.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
	at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:153)
	at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:40)
	at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:98)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
May 16, 2016 4:01:48 PM org.eclipse.jetty.util.log.JavaUtilLog warn
WARNING: Ignoring extra content ��
May 16, 2016 4:01:48 PM org.eclipse.jetty.util.log.JavaUtilLog warn
WARNING: Ignoring extra content ����R0�)"�

May 16, 2016 4:45:44 PM org.eclipse.jetty.util.log.JavaUtilLog warn
WARNING: Ignoring extra content ��
May 16, 2016 4:45:44 PM org.eclipse.jetty.util.log.JavaUtilLog warn
WARNING: Ignoring extra content ����R0�)"�
```

**Comment by jimmidyson** [comment]
Is there any corresponding errors in the API server? I assume it doesn't recover at all (as it should do!)?

**Comment by spadgett** [comment]
I don't see anything that looks like it matches in the API server log. It doesn't recover :(

**Comment by ALRubinger** [comment]
Ping on this @jimmidyson ?

**Comment by spadgett** [comment]
Hit this again today. It happens every few days. Same stack trace each time.

**Comment by jimmidyson** [comment]
Sorry haven't looked at this - guess this is related to the disabling of the read timeout in the client & wrongly swallowing an exception rather than reconnecting. Will try to find time to look this week.

**Comment by ALRubinger** [comment]
Thanks very much, Jimmi.

**Comment by jimmidyson** [comment]
Just releasing latest kubernetes client with what I hope should be a fix for this. Haven't been able to reproduce it though so not 100% sure.

**Comment by spadgett** [comment]
@jimmidyson thanks, we can verify the fix if you have an updated plugin to install

**Comment by jimmidyson** [comment]
Closing this now as I'm pretty sure it's sorted.
