### ISSUE TITLE
classcastexception updating buildconfig

### ISSUE THREAD

**Issue by bparees** [fabric8io/openshift-jenkins-sync-plugin#67]
occurs using the latest version of the plugin, and no kubernetes namespace set (emptystring).

```
INFO: Updating BuildConfig in namespace: pipelineproject with name: sample-pipeline
May 24, 2016 10:00:09 PM io.fabric8.jenkins.openshiftsync.PipelineJobListener upsertBuildConfigForJob
WARNING: Failed to update BuildConfig: NamespaceName{pipelineproject:sample-pipeline}. io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:57)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:112)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:32)
	at io.fabric8.jenkins.openshiftsync.PipelineJobListener.upsertBuildConfigForJob(PipelineJobListener.java:117)
	at io.fabric8.jenkins.openshiftsync.PipelineJobListener.upsertItem(PipelineJobListener.java:93)
	at io.fabric8.jenkins.openshiftsync.PipelineJobListener.onCreated(PipelineJobListener.java:62)
	at hudson.model.listeners.ItemListener$2.apply(ItemListener.java:186)
	at hudson.model.listeners.ItemListener$2.apply(ItemListener.java:184)
	at hudson.model.listeners.ItemListener.forAll(ItemListener.java:167)
	at hudson.model.listeners.ItemListener.fireOnCreated(ItemListener.java:184)
	at hudson.model.ItemGroupMixIn.createProjectFromXML(ItemGroupMixIn.java:280)
	at jenkins.model.Jenkins.createProjectFromXML(Jenkins.java:3105)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$1.call(BuildConfigWatcher.java:115)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$1.call(BuildConfigWatcher.java:99)
	at hudson.security.ACL.impersonate(ACL.java:213)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher.upsertJob(BuildConfigWatcher.java:99)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher.onInitialBuildConfigs(BuildConfigWatcher.java:68)
	at io.fabric8.jenkins.openshiftsync.GlobalPluginConfiguration$1.run(GlobalPluginConfiguration.java:172)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:93)
	... 23 more
Caused by: java.lang.ClassCastException: io.fabric8.openshift.api.model.BuildTriggerPolicy cannot be cast to io.fabric8.openshift.api.model.BuildTriggerPolicy
	at io.fabric8.openshift.api.model.BuildConfigSpecFluentImpl.withTriggers(BuildConfigSpecFluentImpl.java:156)
	at io.fabric8.openshift.api.model.BuildConfigSpecBuilder.<init>(BuildConfigSpecBuilder.java:42)
	at io.fabric8.openshift.api.model.BuildConfigFluentImpl.withSpec(BuildConfigFluentImpl.java:63)
	at io.fabric8.openshift.api.model.BuildConfigBuilder.<init>(BuildConfigBuilder.java:32)
	at io.fabric8.openshift.api.model.DoneableBuildConfig.<init>(DoneableBuildConfig.java:20)
	... 28 more

May 24, 2016 10:00:09 PM io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$1 call
```

**Comment by bparees** [comment]
(also the slave never gets launched.  if i set the kubernetes namespace, things work fine)

**Comment by jimmidyson** [comment]
java.lang.ClassCastException: io.fabric8.openshift.api.model.BuildTriggerPolicy cannot be cast to io.fabric8.openshift.api.model.BuildTriggerPolicy

looks like there are multiple kubernetes-model JARs in the classpath somehow.

**Comment by ALRubinger** [comment]
@xcoulon reports this one is blocking the Catapult application from working correctly; is this issue set up for triage and we're all aware?  @jimmidyson @bparees
