### ISSUE TITLE
slave pods aren't defaulting to the jenkins pod's namespace

### ISSUE THREAD

**Issue by bparees** [fabric8io/openshift-jenkins-sync-plugin#68]
I'm not sure this is a sync plugin issue (it seems like a kubernetes plugin issue) but since @jimmidyson has been responsive on it so far:

setting the kubernetes namespace to "" is supposed to result in the slave pods using the same namespace as the jenkins pod, but instead it appears to fail:

```
io.fabric8.kubernetes.client.KubernetesClientException: Error accessing: https://kubernetes.default/api/v1/namespaces/pods?labelSelector=jenkins%3Dslave,due to:Forbidden!Configured service account doesn't have access. Service account may have been revoked.
  at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.assertResponseCode(BaseOperation.java:489)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.list(BaseOperation.java:366)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.list(BaseOperation.java:52)
        at org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud.addProvisionedSlave(KubernetesCloud.java:416)
        at org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud.provision(KubernetesCloud.java:297)
```

from @jimmidyson in irc:
> looks it's using an empty namespace rather than null - guess we should handle that too

@jimmidyson also suggested:
> try removing the tag from config totally - not sure how it represents null in jenkins config

but that appears to have the same result.

**Comment by bparees** [comment]
(it doesn't seem like this issue belongs to the sync plugin, should it be against the kubernetes plugin?)

**Comment by bparees** [comment]
also it looks like when i removed the namespace field entirely from the config.xml, and then go to manage jenkins, the field is filled in with "jenkins-slave" as the value.

**Comment by bparees** [comment]
This is being fixed for now via startup logic that sets the right value in the config.xml here:
https://github.com/openshift/jenkins/pull/116

and long term should be fixed by:
https://github.com/jenkinsci/kubernetes-plugin/pull/59
